// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1) {
  return window['go']['desktop']['CategoryHandler']['CreateCategory'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['desktop']['CategoryHandler']['DeleteCategory'](arg1);
}

export function GetAllCategories() {
  return window['go']['desktop']['CategoryHandler']['GetAllCategories']();
}

export function GetCategoryByID(arg1) {
  return window['go']['desktop']['CategoryHandler']['GetCategoryByID'](arg1);
}

export function UpdateCategory(arg1) {
  return window['go']['desktop']['CategoryHandler']['UpdateCategory'](arg1);
}
