// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {category} from '../models';

export function CreateCategory(arg1:category.Category):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function GetAllCategories():Promise<Array<category.Category>>;

export function GetCategoryByID(arg1:number):Promise<category.Category>;

export function UpdateCategory(arg1:category.Category):Promise<void>;
