// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDevice(arg1) {
  return window['go']['desktop']['DeviceHandler']['CreateDevice'](arg1);
}

export function DeleteDevice(arg1) {
  return window['go']['desktop']['DeviceHandler']['DeleteDevice'](arg1);
}

export function GetAllDevices() {
  return window['go']['desktop']['DeviceHandler']['GetAllDevices']();
}

export function GetDeviceByID(arg1) {
  return window['go']['desktop']['DeviceHandler']['GetDeviceByID'](arg1);
}

export function GetDevicesByEmployeeID(arg1) {
  return window['go']['desktop']['DeviceHandler']['GetDevicesByEmployeeID'](arg1);
}

export function UpdateDevice(arg1) {
  return window['go']['desktop']['DeviceHandler']['UpdateDevice'](arg1);
}
