// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {device} from '../models';

export function CreateDevice(arg1:device.Device):Promise<void>;

export function DeleteDevice(arg1:number):Promise<void>;

export function GetAllDevices():Promise<Array<device.Device>>;

export function GetDeviceByID(arg1:number):Promise<device.Device>;

export function GetDevicesByEmployeeID(arg1:number):Promise<Array<device.Device>>;

export function UpdateDevice(arg1:device.Device):Promise<void>;
