// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {employee} from '../models';
import {context} from '../models';

export function CreateEmployee(arg1:employee.Employee):Promise<void>;

export function WailsInit(arg1:context.Context):Promise<void>;
