// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';

export function CreateProject(arg1:project.Project):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function GetAllProjects():Promise<Array<project.Project>>;

export function GetProjectByID(arg1:number):Promise<project.Project>;

export function UpdateProject(arg1:project.Project):Promise<void>;
