// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {projectemployee} from '../models';

export function CreateProjectEmployee(arg1:projectemployee.ProjectEmployee):Promise<void>;

export function DeleteProjectEmployee(arg1:number):Promise<void>;

export function GetAllProjectEmployees():Promise<Array<projectemployee.ProjectEmployee>>;

export function GetProjectEmployeeByID(arg1:number):Promise<projectemployee.ProjectEmployee>;

export function GetProjectEmployeesByEmployeeID(arg1:number):Promise<Array<projectemployee.ProjectEmployee>>;

export function GetProjectEmployeesByProjectID(arg1:number):Promise<Array<projectemployee.ProjectEmployee>>;

export function UpdateProjectEmployee(arg1:projectemployee.ProjectEmployee):Promise<void>;
