// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['desktop']['ProjectHandler']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['desktop']['ProjectHandler']['DeleteProject'](arg1);
}

export function GetAllProjects() {
  return window['go']['desktop']['ProjectHandler']['GetAllProjects']();
}

export function GetProjectByID(arg1) {
  return window['go']['desktop']['ProjectHandler']['GetProjectByID'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['desktop']['ProjectHandler']['UpdateProject'](arg1);
}
