// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProjectEmployee(arg1) {
  return window['go']['desktop']['ProjectEmployeeHandler']['CreateProjectEmployee'](arg1);
}

export function DeleteProjectEmployee(arg1) {
  return window['go']['desktop']['ProjectEmployeeHandler']['DeleteProjectEmployee'](arg1);
}

export function GetAllProjectEmployees() {
  return window['go']['desktop']['ProjectEmployeeHandler']['GetAllProjectEmployees']();
}

export function GetProjectEmployeeByID(arg1) {
  return window['go']['desktop']['ProjectEmployeeHandler']['GetProjectEmployeeByID'](arg1);
}

export function GetProjectEmployeesByEmployeeID(arg1) {
  return window['go']['desktop']['ProjectEmployeeHandler']['GetProjectEmployeesByEmployeeID'](arg1);
}

export function GetProjectEmployeesByProjectID(arg1) {
  return window['go']['desktop']['ProjectEmployeeHandler']['GetProjectEmployeesByProjectID'](arg1);
}

export function UpdateProjectEmployee(arg1) {
  return window['go']['desktop']['ProjectEmployeeHandler']['UpdateProjectEmployee'](arg1);
}
