// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHistoryForEmployee(arg1) {
  return window['go']['desktop']['RfidCardHistoryHandler']['GetHistoryForEmployee'](arg1);
}

export function RegisterAssignment(arg1) {
  return window['go']['desktop']['RfidCardHistoryHandler']['RegisterAssignment'](arg1);
}
