// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRfidCard(arg1) {
  return window['go']['desktop']['RfidCardHandler']['CreateRfidCard'](arg1);
}

export function DeleteRfidCard(arg1) {
  return window['go']['desktop']['RfidCardHandler']['DeleteRfidCard'](arg1);
}

export function GetAllRfidCards() {
  return window['go']['desktop']['RfidCardHandler']['GetAllRfidCards']();
}

export function GetRfidCardByID(arg1) {
  return window['go']['desktop']['RfidCardHandler']['GetRfidCardByID'](arg1);
}

export function GetRfidCardByUUID(arg1) {
  return window['go']['desktop']['RfidCardHandler']['GetRfidCardByUUID'](arg1);
}

export function UpdateRfidCard(arg1) {
  return window['go']['desktop']['RfidCardHandler']['UpdateRfidCard'](arg1);
}
