// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rfidcardhistory} from '../models';

export function GetHistoryForEmployee(arg1:number):Promise<Array<rfidcardhistory.RfidCardHistory>>;

export function RegisterAssignment(arg1:rfidcardhistory.RfidCardHistory):Promise<void>;
