// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rfidcard} from '../models';

export function CreateRfidCard(arg1:rfidcard.RfidCard):Promise<void>;

export function DeleteRfidCard(arg1:number):Promise<void>;

export function GetAllRfidCards():Promise<Array<rfidcard.RfidCard>>;

export function GetRfidCardByID(arg1:number):Promise<rfidcard.RfidCard>;

export function GetRfidCardByUUID(arg1:string):Promise<rfidcard.RfidCard>;

export function UpdateRfidCard(arg1:rfidcard.RfidCard):Promise<void>;
